### ISSUE TITLE
docker-ce binaries are no longer distributed for RHEL on x86_64

### ISSUE THREAD

**Issue by chris968** [robertdebock/ansible-role-docker_ce#10]
## Bug description

the docker-ce binaries are no longer available from the official yum/dnf docker repositories for RHEL on the x86_64 architecture.

c.f. [(https://docs.docker.com/engine/install/rhel/](https://docs.docker.com/engine/install/rhel/)

It's working when running the playbook with `-e docker_ce_dist="centos"`

## Playbook

```yaml
- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars/vault.yml
  pre_tasks:
    - name: Disable NetworkManager
      systemd:
        name: NetworkManager
        state: stopped
        enabled: no
        masked: yes
      when: networkmanager_enabled is defined and not networkmanager_enabled
  roles:
    - role: robertdebock.core_dependencies
    - role: robertdebock.common
    - role: robertdebock.selinux
    - role: robertdebock.buildtools
    - role: robertdebock.cron
    - role: robertdebock.ntp
    - role: robertdebock.epel
    - role: itigoag.packages
      tags: packages
    - role: freeipa-client
      when: "'freeipa_clients' in group_names"
      tags: auth
    - role: stackhpc.libvirt-host
      when: "'libvirt_hosts' in group_names"
      tags: virt
    - role: robertdebock.python_pip
      when: "'docker_hosts' in group_names"
    - role: robertdebock.docker_ce
      when: "'docker_hosts' in group_names"
      tags: container
    - role: common
    - role: tessares_server
  tasks:
    - name: add user to libvirt group
      user:
        name: "{{ item.name }}"
        groups: libvirt
        append: yes
      loop: "{{ libvirt_users|default([])|union(administrators)|list|unique }}"
      when: "'libvirt_hosts' in group_names"
      tags: virt

```

## Output

```
TASK [robertdebock.docker_ce : install docker_ce packages] *************************************************************************************************************************************************************************************************************************
fatal: [openstack12]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
```

## Environment

- Control node OS: Ubuntu 20.04.2 LTS
- Control node Ansible version: ansible 4.3.0 (ansible-core-2.11.3)
- Managed node OS: Rocky Linux 8.4

**Comment by robertdebock** [comment]
Hm, I just reran CI tests on both [gitlab](https://gitlab.com/robertdebock/ansible-role-docker_ce/-/jobs/1532094030) and [github](https://github.com/robertdebock/ansible-role-docker_ce/runs/3418995636?check_suite_focus=true) and both finished succesfully.

I can't test on RHEL because of the subscription required.

What can I change to reproduce the issue?

**Comment by chris968** [comment]
The problem occur on RHEL and Rocky Linux because it considered as RHEL by your role, you might add a Rocky Linux test in molecule if it is possible

**Comment by b1r63r** [comment]
On RHEL the only architecture supported by docker is s390x (IBM mainframe)
For all other architectures (aarch64, ppc64le, x86_64 exist right now) you must simply replace rhel with centos in the url when fetching the repo file.

**Comment by b1r63r** [comment]
Easy workaround right now is to add the following before calling the docker_ce role. The role will then see that the repo is there already.
```
- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
```
