### ISSUE TITLE
No setuptools found in remote host

### ISSUE THREAD

**Issue by sawicki-maciej** [robertdebock/ansible-role-docker_ce#3]
**Describe the bug**
TASK [robertdebock.docker_ce : install docker pip packages] *********************************************************************************************************************************************************************************
FAILED - RETRYING: install docker pip packages (3 retries left).
FAILED - RETRYING: install docker pip packages (2 retries left).
FAILED - RETRYING: install docker pip packages (1 retries left).
fatal: [ubuntu-s-1vcpu-2gb-fra1-01]: FAILED! => {"attempts": 3, "changed": false, "msg": "No setuptools found in remote host, please install it first."}

**To Reproduce**
---
- name: bootstrap all hosts
  hosts: linux
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.docker_ce
   ansible-playbook playbook.yaml -u root
ubuntu 18.04 on digital ocean

**Expected behavior**

**Error**
Please show the resulting error. If applicable a snippet of the playbook including the role ran with `-vvv`

**Environment**
- Control node OS: [e.g. Debian 9]
- Control node Ansible version: [e.g. 2.6.2]
- Managed node OS: [e.g. CentOS 7]

**Additional context**

**Comment by robertdebock** [comment]
Hi, thanks for your issue. The machine you are running this role on, should be prepared. You can do this using other roles, or these. (Copy-paste from README.md)

```
---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes
  serial: 30%

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
```

Please reopen when this does not solve your issue.
